language: ruby
os: linux
cache:
  bundler: true
  rvm: ".rvm"
rvm:
  - 2.6.5
services:
  - postgresql

branches:
  only:
    - master

# Lifecycle
before_install:
  - gem install bundler
  - echo $env_key | gpg --passphrase-fd 0 ./.env.gpg
before_script:
  - psql -c "CREATE USER esm WITH ENCRYPTED PASSWORD 'password12345'; ALTER USER esm WITH SUPERUSER;" -U postgres
script:
  - bin/setup
  - bin/test


# ENV Variables
env:
  global:
    secure: nw06MNFdF2ygAh+zHfwwH7bozhT3/r5nJk8M9zkDehrUbCxxKhUtvu1Yj8XQuAhX5xAz3hQjmHmWDIz9x5ZUZHiuBuUwfE513uDRiQaQj1VN/0glS6srCp37hEKpgSUILVUEK8wIXdGUmS1mylA2QmwsLREh4FDBL1KRhCbDln9S0AIPuaEBvoSQpuzsqpWDNgFeYsByXO00GjmwiNFUqE/pdiiwGkLmH2SsSIVP1pfU4IEjk/S+47AmmVxyk8tRIql1K0VeK5gBT3TKRFphECY0IwSkkYPk/M249AbdJEOvsuKzlMQqLwiB9CFTYVuxAMek95nZOT0ssvOPV/z/+22UrGTZmMHhk+WjUtFhrm3j+FVndI2FccM+3mBq05AanRMrEYkc3LLfuNxa/xM02UPgUJjDiaDuonEo36wmF/bDjmolsYicZ52iGD6Ri5ujD2ci9I9UfXKN/YDhbk+ghNiVqSl1YBt7ytdemiIjvBTMMiiZ1cE+Ke5I5X0xzKrUVr7cQQ8wsTgbLXOSdVkAr0kkrJ+3P8Iy3P0I/g47jWb7KFIckdY1/b9/0M2PKt7MQU/DUqvKm873OBQIzTk8Vwbx7u+QGg5SGBCivXHWPFkAPs1x/Iw0FEfjmsannYQCROidgiqqXdVC1J+sXUYREnB7XmQlxuiyyrDRkWcod9g=
